#!/usr/bin/env bash
# WebSearch — Nginx 反代配置（可单独运行，或由 setup-vps.sh 调用）
# 用法: sudo bash deploy/nginx/setup-nginx.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=deploy/lib/common.sh
source "$SCRIPT_DIR/../lib/common.sh"
# shellcheck source=deploy/lib/nginx-cert.sh
source "$SCRIPT_DIR/../lib/nginx-cert.sh"

check_nginx() {
    if command -v nginx >/dev/null 2>&1; then
        ok "已检测到 Nginx: $(nginx -v 2>&1)"
        return 0
    fi

    warn "未检测到 Nginx。"
    if prompt_yn "是否现在安装 Nginx + Certbot? (Ubuntu/Debian apt)" "y"; then
        apt-get update
        apt-get install -y nginx certbot python3-certbot-nginx
        ok "Nginx 与 Certbot 安装完成"
    else
        err "请先安装 Nginx 后再运行。"
        exit 1
    fi
}

check_backend() {
    local host="$1"
    local port="$2"

    if command -v curl >/dev/null 2>&1; then
        if curl -fsS --max-time 3 "http://${host}:${port}/health" >/dev/null 2>&1; then
            ok "后端 http://${host}:${port}/health 响应正常"
            return 0
        fi
    fi

    warn "无法连接 http://${host}:${port}/health"
    if [[ "${DEPLOY_FROM_SETUP:-}" == "1" ]]; then
        warn "继续配置 Nginx（API 可能仍在启动中）..."
        return 0
    fi
    if ! prompt_yn "后端未就绪，仍继续配置 Nginx?" "n"; then
        exit 1
    fi
}

_write_proxy_location() {
    cat <<'EOF'
        proxy_pass http://websearch_api;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";

        proxy_connect_timeout 60s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
EOF
}

write_nginx_config() {
    local domain="$1"
    local backend_host="$2"
    local backend_port="$3"
    local site_name="$4"
    local use_ssl="${5:-false}"
    local config_path="/etc/nginx/sites-available/${site_name}"

    if [[ "$use_ssl" == "true" ]] && letsencrypt_cert_exists "$domain"; then
        cat > "$config_path" <<EOF
# Generated by WebSearch deploy/nginx/setup-nginx.sh
# Domain: ${domain} (HTTPS — 复用已有证书)

upstream websearch_api {
    server ${backend_host}:${backend_port};
    keepalive 32;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${domain};

    ssl_certificate     /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
$( [[ -f /etc/letsencrypt/options-ssl-nginx.conf ]] && echo "    include /etc/letsencrypt/options-ssl-nginx.conf;" )
$( [[ -f /etc/letsencrypt/ssl-dhparams.pem ]] && echo "    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;" )

    location / {
$(_write_proxy_location | sed 's/^/        /')
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name ${domain};
    return 301 https://\$host\$request_uri;
}
EOF
        ok "已写入 HTTPS 配置（复用已有证书）: ${config_path}"
    else
        cat > "$config_path" <<EOF
# Generated by WebSearch deploy/nginx/setup-nginx.sh
# Domain: ${domain}

upstream websearch_api {
    server ${backend_host}:${backend_port};
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    location / {
$(_write_proxy_location | sed 's/^/        /')
    }
}
EOF
        ok "已写入 ${config_path}"
    fi

    ln -sf "$config_path" "/etc/nginx/sites-enabled/${site_name}"
    ok "已启用 /etc/nginx/sites-enabled/${site_name}"

    if [[ -f /etc/nginx/sites-enabled/default ]]; then
        if [[ "${DEPLOY_FROM_SETUP:-}" == "1" ]]; then
            rm -f /etc/nginx/sites-enabled/default
            ok "已禁用 default 站点"
        elif prompt_yn "是否禁用 Nginx 默认站点 (default)?" "y"; then
            rm -f /etc/nginx/sites-enabled/default
            ok "已禁用 default 站点"
        fi
    fi

    nginx -t
    systemctl reload nginx
    ok "Nginx 已重载"
}

setup_https() {
    local domain="$1"
    local email="$2"

    if letsencrypt_cert_exists "$domain"; then
        info "已有证书，跳过 Certbot 注册: /etc/letsencrypt/live/${domain}/"
        ok "HTTPS 已就绪（复用）: https://${domain}"
        return 0
    fi

    if ! command -v certbot >/dev/null 2>&1; then
        apt-get update
        apt-get install -y certbot python3-certbot-nginx
    fi

    if [[ -z "$email" ]]; then
        if [[ "${DEPLOY_FROM_SETUP:-}" == "1" ]]; then
            err "未找到域名 ${domain} 的已有证书，且 .env 中 CERTBOT_EMAIL 为空，无法新申请证书。"
            return 1
        fi
        prompt CERTBOT_EMAIL "Certbot 邮箱" ""
        email="$CERTBOT_EMAIL"
    fi

    info "正在申请 Let's Encrypt 证书..."
    certbot --nginx -d "$domain" --email "$email" --agree-tos --no-eff-email --redirect --non-interactive
    ok "HTTPS 配置完成: https://${domain}"
}

main() {
    require_root

    echo ""
    echo -e "${CYAN}========================================${NC}"
    echo -e "${CYAN}  WebSearch Nginx 反代配置${NC}"
    echo -e "${CYAN}========================================${NC}"
    echo ""

    if [[ -n "${NGINX_DOMAIN:-}" ]]; then
        DOMAIN="${NGINX_DOMAIN}"
        BACKEND_HOST="${NGINX_BACKEND_HOST:-127.0.0.1}"
        BACKEND_PORT="${NGINX_BACKEND_PORT:-5080}"
        SITE_NAME="${NGINX_SITE_NAME:-websearch}"
        CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"
        ENABLE_HTTPS="${ENABLE_HTTPS:-y}"
    else
        echo "按提示输入，直接回车使用默认值。"
        echo ""
        prompt DOMAIN "API 域名" ""
        prompt BACKEND_HOST "后端地址" "127.0.0.1"
        prompt BACKEND_PORT "后端端口" "5080"
        prompt SITE_NAME "Nginx 站点文件名" "websearch"
        ENABLE_HTTPS="n"
        CERTBOT_EMAIL=""
        if prompt_yn "是否配置 HTTPS (Let's Encrypt)?" "y"; then
            ENABLE_HTTPS="y"
            if letsencrypt_cert_exists "$DOMAIN"; then
                ok "检测到已有证书，将直接复用，无需填写邮箱"
            else
                prompt CERTBOT_EMAIL "Certbot 邮箱" ""
            fi
        fi
    fi

    echo ""
    info "配置预览:"
    echo "  域名:     https://${DOMAIN}"
    echo "  反代到:   http://${BACKEND_HOST}:${BACKEND_PORT}"
    if letsencrypt_cert_exists "$DOMAIN"; then
        echo "  HTTPS:    复用已有证书"
    fi
    echo ""

    if [[ "${DEPLOY_FROM_SETUP:-}" != "1" ]] && [[ -z "${NGINX_DOMAIN:-}" || -z "${DEPLOY_NONINTERACTIVE:-}" ]]; then
        if ! prompt_yn "确认并继续?" "y"; then
            info "已取消。"
            exit 0
        fi
    fi

    check_nginx
    check_backend "$BACKEND_HOST" "$BACKEND_PORT"

    local use_ssl="false"
    if [[ "${ENABLE_HTTPS,,}" == "y" || "${ENABLE_HTTPS}" == "1" ]]; then
        if letsencrypt_cert_exists "$DOMAIN"; then
            use_ssl="true"
        fi
    fi

    write_nginx_config "$DOMAIN" "$BACKEND_HOST" "$BACKEND_PORT" "$SITE_NAME" "$use_ssl"

    if [[ "${ENABLE_HTTPS,,}" == "y" || "${ENABLE_HTTPS}" == "1" ]]; then
        setup_https "$DOMAIN" "$CERTBOT_EMAIL"
    fi
}

main "$@"
