#!/usr/bin/env bash
# 交互式生成 .env（由 setup-vps.sh 调用）
# API 容器使用 host 网络，所有服务均通过 localhost 访问。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/detect-infra.sh"
source "$SCRIPT_DIR/lib/nginx-cert.sh"

# ---------- write / sync ----------

write_env_file() {
    local env_file="$PROJECT_ROOT/.env"

    cat > "$env_file" <<EOF
# Generated by WebSearch deploy/configure-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# API 容器使用 host 网络 — 所有服务均通过 localhost 访问

USE_BUILTIN_REDIS=${USE_BUILTIN_REDIS}
USE_BUILTIN_POSTGRES=${USE_BUILTIN_POSTGRES}
REDIS_CONNECTION=${REDIS_CONNECTION}
POSTGRES_CONNECTION=${POSTGRES_CONNECTION}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}

FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY:-}
JINA_API_KEY=${JINA_API_KEY:-}

CACHE_SEARCH_TTL=${CACHE_SEARCH_TTL}
CACHE_SCRAPE_TTL=${CACHE_SCRAPE_TTL}

API_DOMAIN=${API_DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL:-}
NGINX_SITE_NAME=${NGINX_SITE_NAME:-websearch}
WEBSEARCH_API_URL=https://${API_DOMAIN}
EOF

    chmod 600 "$env_file"
    ok "已写入 ${env_file}"
}

update_searxng_secret() {
    local settings="$PROJECT_ROOT/deploy/searxng/settings.yml"
    [[ -f "$settings" ]] || return 0
    if grep_safe -q 'secret_key:' "$settings"; then
        sed -i "s|secret_key:.*|secret_key: \"${SEARXNG_SECRET_KEY}\"|" "$settings"
        ok "已同步 SearXNG secret_key → deploy/searxng/settings.yml"
    fi
}

# ---------- configure steps ----------

configure_redis() {
    step "[1/4] Redis 配置"
    echo "  API 容器使用 host 网络，通过 localhost:6379 访问 Redis。"
    echo ""

    local detected=""
    detected="$(describe_existing_redis 2>/dev/null || true)"

    if [[ -n "$detected" ]]; then
        # 端口已被占用 — 不能再新建内置容器，只能使用已有服务
        info "检测到端口 6379 已被占用:"
        echo "  ${detected}"
        echo ""
        warn "端口 6379 已占用，不能新建内置 Redis 容器（会冲突）。"
        info "API 将通过 localhost:6379 直接连接上方服务。"
        USE_BUILTIN_REDIS=false
        prompt REDIS_CONNECTION "Redis 连接串（回车使用默认）" "localhost:6379,abortConnect=false"
        ok "将使用已有 Redis: ${REDIS_CONNECTION}"
        return
    fi

    # 端口空闲，可以选择
    info "未检测到 6379 端口上的 Redis 服务。"
    if prompt_yn "使用外部 Redis（已有服务，不新建容器）?" "n"; then
        USE_BUILTIN_REDIS=false
        prompt REDIS_CONNECTION "Redis 连接串" "localhost:6379,abortConnect=false"
        ok "将连接外部 Redis: ${REDIS_CONNECTION}"
        return
    fi

    USE_BUILTIN_REDIS=true
    REDIS_CONNECTION="localhost:6379,abortConnect=false"
    ok "将新建内置 Redis 容器（监听 127.0.0.1:6379）"
}

configure_postgres() {
    step "[2/4] PostgreSQL 配置"
    echo "  API 容器使用 host 网络，通过 localhost:5432 访问 PostgreSQL。"
    echo ""

    local detected=""
    detected="$(describe_existing_postgres 2>/dev/null || true)"

    if [[ -n "$detected" ]]; then
        # 端口已被占用 — 不能再新建内置容器，只能使用已有服务
        info "检测到端口 5432 已被占用:"
        echo "  ${detected}"
        echo ""
        warn "端口 5432 已占用，不能新建内置 PostgreSQL 容器（会冲突）。"
        info "API 将通过 localhost:5432 直接连接上方服务。"
        echo ""

        USE_BUILTIN_POSTGRES=false
        local pg_database pg_username
        prompt pg_database "数据库名" "websearch"
        prompt pg_username "用户名"   "websearch"
        read -r -s -p "密码: " POSTGRES_PASSWORD; echo ""

        POSTGRES_CONNECTION="Host=localhost;Port=5432;Database=${pg_database};Username=${pg_username};Password=${POSTGRES_PASSWORD}"

        # 检测是否是 Docker 容器——可以帮助自动创建 DB
        local container_name
        container_name="$(detect_docker_container_on_port 5432 2>/dev/null | awk '{print $1}' || true)"
        if [[ -n "$container_name" ]] && prompt_yn "检测到容器 ${container_name}，是否自动在其中创建数据库和用户?" "y"; then
            _auto_create_pg_db "$container_name" "$pg_database" "$pg_username" "$POSTGRES_PASSWORD"
        else
            echo ""
            info "请手动在 PostgreSQL 中执行:"
            echo "  CREATE DATABASE ${pg_database};"
            echo "  CREATE USER ${pg_username} WITH PASSWORD '${POSTGRES_PASSWORD}';"
            echo "  GRANT ALL PRIVILEGES ON DATABASE ${pg_database} TO ${pg_username};"
        fi

        ok "将使用已有 PostgreSQL: ${POSTGRES_CONNECTION//Password=*/Password=***}"
        return
    fi

    # 端口空闲，可以选择
    info "未检测到 5432 端口上的 PostgreSQL 服务。"
    if prompt_yn "使用外部 PostgreSQL（已有服务，不新建容器）?" "n"; then
        USE_BUILTIN_POSTGRES=false
        local pg_port pg_database pg_username
        prompt pg_port     "端口"   "5432"
        prompt pg_database "数据库名" "websearch"
        prompt pg_username "用户名"  "websearch"
        read -r -s -p "密码: " POSTGRES_PASSWORD; echo ""
        POSTGRES_CONNECTION="Host=localhost;Port=${pg_port};Database=${pg_database};Username=${pg_username};Password=${POSTGRES_PASSWORD}"
        ok "将连接外部 PostgreSQL"
        return
    fi

    USE_BUILTIN_POSTGRES=true
    read -r -s -p "内置 PostgreSQL 密码（回车自动生成）: " POSTGRES_PASSWORD; echo ""
    [[ -z "$POSTGRES_PASSWORD" ]] && POSTGRES_PASSWORD="$(generate_secret)"
    POSTGRES_CONNECTION="Host=localhost;Port=5432;Database=websearch;Username=websearch;Password=${POSTGRES_PASSWORD}"
    ok "将新建内置 PostgreSQL 容器（监听 127.0.0.1:5432）"
}

# 在目标容器中自动创建数据库和用户（仅当用户确认）
_auto_create_pg_db() {
    local container="$1" db="$2" user="$3" pass="$4"
    info "在 ${container} 中创建 ${db} 数据库..."
    docker exec "$container" psql -U postgres \
        -c "CREATE DATABASE ${db};" 2>/dev/null \
        && ok "数据库 ${db} 已创建" \
        || warn "数据库 ${db} 可能已存在，跳过"
    docker exec "$container" psql -U postgres \
        -c "DROP USER IF EXISTS ${user};" 2>/dev/null || true
    docker exec "$container" psql -U postgres \
        -c "CREATE USER ${user} WITH PASSWORD '${pass}';"
    docker exec "$container" psql -U postgres \
        -c "GRANT ALL PRIVILEGES ON DATABASE ${db} TO ${user};"
    ok "用户 ${user} 已创建并授权"
}

run_configure_env_interactive() {
    configure_redis
    configure_postgres

    step "[3/4] 密钥与可选 API Key"
    read -r -s -p "SearXNG 密钥（回车自动生成）: " SEARXNG_SECRET_KEY; echo ""
    [[ -z "$SEARXNG_SECRET_KEY" ]] && SEARXNG_SECRET_KEY="$(generate_secret)"
    ok "SearXNG 密钥已设置"
    prompt_optional FIRECRAWL_API_KEY "Firecrawl API Key"
    prompt_optional JINA_API_KEY "Jina API Key"
    prompt CACHE_SEARCH_TTL "搜索缓存 TTL（秒）" "7200"
    prompt CACHE_SCRAPE_TTL "抓取缓存 TTL（秒）" "86400"

    step "[4/4] 域名与 HTTPS"
    echo "请确保域名 A 记录已指向本 VPS IP。"
    echo ""
    prompt API_DOMAIN "API 域名（如 api.example.com）" ""
    CERTBOT_EMAIL=""
    if letsencrypt_cert_exists "$API_DOMAIN"; then
        ok "检测到已有证书 /etc/letsencrypt/live/${API_DOMAIN}/，将直接复用，无需填邮箱"
    else
        prompt CERTBOT_EMAIL "Certbot 邮箱（HTTPS 证书通知）" ""
    fi
    NGINX_SITE_NAME="websearch"

    step "确认配置"
    echo "  Redis:        $([[ "$USE_BUILTIN_REDIS" == "true" ]] && echo '新建内置容器' || echo "外部 → ${REDIS_CONNECTION}")"
    echo "  PostgreSQL:   $([[ "$USE_BUILTIN_POSTGRES" == "true" ]] && echo '新建内置容器' || echo '外部 → localhost:5432')"
    echo "  SearXNG 密钥: (已设置)"
    echo "  搜索缓存 TTL: ${CACHE_SEARCH_TTL}s"
    echo "  API 域名:     https://${API_DOMAIN}"
    if letsencrypt_cert_exists "$API_DOMAIN"; then
        echo "  HTTPS 证书:   复用已有"
    else
        echo "  Certbot 邮箱: ${CERTBOT_EMAIL}"
    fi
    echo ""

    if ! prompt_yn "确认写入 .env 并开始部署?" "y"; then
        info "已取消。"; exit 0
    fi

    write_env_file
    update_searxng_secret
}

run_configure_env_from_env() {
    : "${API_DOMAIN:?API_DOMAIN required}"
    if ! letsencrypt_cert_exists "${API_DOMAIN:-}"; then
        : "${CERTBOT_EMAIL:?CERTBOT_EMAIL required when no existing certificate}"
    fi
    CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"
    USE_BUILTIN_REDIS="${USE_BUILTIN_REDIS:-true}"
    USE_BUILTIN_POSTGRES="${USE_BUILTIN_POSTGRES:-true}"
    SEARXNG_SECRET_KEY="${SEARXNG_SECRET_KEY:-$(generate_secret)}"
    FIRECRAWL_API_KEY="${FIRECRAWL_API_KEY:-}"
    JINA_API_KEY="${JINA_API_KEY:-}"
    CACHE_SEARCH_TTL="${CACHE_SEARCH_TTL:-7200}"
    CACHE_SCRAPE_TTL="${CACHE_SCRAPE_TTL:-86400}"
    NGINX_SITE_NAME="${NGINX_SITE_NAME:-websearch}"

    if [[ "$USE_BUILTIN_REDIS" == "true" ]]; then
        REDIS_CONNECTION="${REDIS_CONNECTION:-localhost:6379,abortConnect=false}"
    else
        REDIS_CONNECTION="${REDIS_CONNECTION:-localhost:6379,abortConnect=false}"
    fi

    if [[ "$USE_BUILTIN_POSTGRES" == "true" ]]; then
        : "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required for builtin postgres}"
        POSTGRES_CONNECTION="${POSTGRES_CONNECTION:-Host=localhost;Port=5432;Database=websearch;Username=websearch;Password=${POSTGRES_PASSWORD}}"
    else
        : "${POSTGRES_CONNECTION:?POSTGRES_CONNECTION required for external postgres}"
        POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
    fi

    write_env_file
    update_searxng_secret
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cd "$PROJECT_ROOT"
    if [[ -n "${API_DOMAIN:-}" ]]; then
        run_configure_env_from_env
    else
        run_configure_env_interactive
    fi
fi
