#!/usr/bin/env bash
# 交互式生成 .env 并同步 SearXNG 密钥（由 setup-vps.sh 调用）

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=deploy/lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

write_env_file() {
    local env_file="$PROJECT_ROOT/.env"

    cat > "$env_file" <<EOF
# Generated by deploy/setup-vps.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}

FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
JINA_API_KEY=${JINA_API_KEY}

CACHE_SEARCH_TTL=${CACHE_SEARCH_TTL}
CACHE_SCRAPE_TTL=${CACHE_SCRAPE_TTL}

API_DOMAIN=${API_DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}
WEBSEARCH_API_URL=https://${API_DOMAIN}
EOF

    chmod 600 "$env_file"
    ok "已写入 ${env_file}"
}

update_searxng_secret() {
    local settings="$PROJECT_ROOT/deploy/searxng/settings.yml"
    if [[ ! -f "$settings" ]]; then
        warn "未找到 ${settings}，跳过 SearXNG 密钥同步。"
        return 0
    fi

    if grep -q 'secret_key:' "$settings"; then
        sed -i "s|secret_key:.*|secret_key: \"${SEARXNG_SECRET_KEY}\"|" "$settings"
    else
        warn "settings.yml 中无 secret_key 字段，请手动检查。"
        return 0
    fi

    ok "已同步 SearXNG secret_key → deploy/searxng/settings.yml"
}

run_configure_env_interactive() {
    step "[1/3] 服务密钥与 API Key"

    echo "以下两项直接回车将自动生成随机强密码。"
    echo ""

    prompt POSTGRES_PASSWORD "PostgreSQL 密码" "" "true"
    [[ -z "${POSTGRES_PASSWORD}" ]] && POSTGRES_PASSWORD="$(generate_secret)"
    ok "PostgreSQL 密码已设置"

    prompt SEARXNG_SECRET_KEY "SearXNG 密钥" "" "true"
    [[ -z "${SEARXNG_SECRET_KEY}" ]] && SEARXNG_SECRET_KEY="$(generate_secret)"
    ok "SearXNG 密钥已设置"

    prompt_optional FIRECRAWL_API_KEY "Firecrawl API Key"
    prompt_optional JINA_API_KEY "Jina API Key"

    prompt CACHE_SEARCH_TTL "搜索缓存 TTL（秒）" "7200"
    prompt CACHE_SCRAPE_TTL "抓取缓存 TTL（秒）" "86400"

    step "[2/3] 域名与 HTTPS"

    echo "请确保域名 A 记录已指向本 VPS IP。"
    echo ""

    prompt API_DOMAIN "API 域名（如 api.example.com）" ""
    prompt CERTBOT_EMAIL "Certbot 邮箱（HTTPS 证书到期提醒）" ""

    step "[3/3] 确认配置"

    echo "  PostgreSQL 密码:  (已设置，共 ${#POSTGRES_PASSWORD} 字符)"
    echo "  SearXNG 密钥:      (已设置)"
    echo "  Firecrawl Key:     ${FIRECRAWL_API_KEY:-<未设置>}"
    echo "  Jina Key:          ${JINA_API_KEY:-<未设置>}"
    echo "  搜索缓存 TTL:      ${CACHE_SEARCH_TTL}s"
    echo "  抓取缓存 TTL:      ${CACHE_SCRAPE_TTL}s"
    echo "  API 域名:          https://${API_DOMAIN}"
    echo "  Certbot 邮箱:      ${CERTBOT_EMAIL}"
    echo ""

    if ! prompt_yn "确认写入 .env 并开始部署?" "y"; then
        info "已取消。"
        exit 0
    fi

    write_env_file
    update_searxng_secret
}

# 非交互：由环境变量传入
run_configure_env_from_env() {
    : "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required}"
    : "${API_DOMAIN:?API_DOMAIN required}"
    : "${CERTBOT_EMAIL:?CERTBOT_EMAIL required}"

    SEARXNG_SECRET_KEY="${SEARXNG_SECRET_KEY:-$(generate_secret)}"
    FIRECRAWL_API_KEY="${FIRECRAWL_API_KEY:-}"
    JINA_API_KEY="${JINA_API_KEY:-}"
    CACHE_SEARCH_TTL="${CACHE_SEARCH_TTL:-7200}"
    CACHE_SCRAPE_TTL="${CACHE_SCRAPE_TTL:-86400}"

    write_env_file
    update_searxng_secret
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cd "$PROJECT_ROOT"
    if [[ -n "${POSTGRES_PASSWORD:-}" && -n "${API_DOMAIN:-}" ]]; then
        run_configure_env_from_env
    else
        run_configure_env_interactive
    fi
fi
