#!/usr/bin/env bash
# 交互式生成 .env 并同步 SearXNG 密钥（由 setup-vps.sh 调用）

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=deploy/lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck source=deploy/lib/detect-infra.sh
source "$SCRIPT_DIR/lib/detect-infra.sh"
# shellcheck source=deploy/lib/nginx-cert.sh
source "$SCRIPT_DIR/lib/nginx-cert.sh"

write_env_file() {
    local env_file="$PROJECT_ROOT/.env"
    local q_redis q_pg_conn q_pg_pass q_searx q_firecrawl q_jina

    q_redis="$(env_quote "$REDIS_CONNECTION")"
    q_pg_conn="$(env_quote "$POSTGRES_CONNECTION")"
    q_pg_pass="$(env_quote "$POSTGRES_PASSWORD")"
    q_searx="$(env_quote "$SEARXNG_SECRET_KEY")"
    q_firecrawl="$(env_quote "${FIRECRAWL_API_KEY:-}")"
    q_jina="$(env_quote "${JINA_API_KEY:-}")"

    cat > "$env_file" <<EOF
# Generated by deploy/setup-vps.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

USE_BUILTIN_REDIS=${USE_BUILTIN_REDIS}
USE_BUILTIN_POSTGRES=${USE_BUILTIN_POSTGRES}
REDIS_CONNECTION=${q_redis}
POSTGRES_CONNECTION=${q_pg_conn}
POSTGRES_PASSWORD=${q_pg_pass}

SEARXNG_SECRET_KEY=${q_searx}

FIRECRAWL_API_KEY=${q_firecrawl}
JINA_API_KEY=${q_jina}

CACHE_SEARCH_TTL=${CACHE_SEARCH_TTL}
CACHE_SCRAPE_TTL=${CACHE_SCRAPE_TTL}

API_DOMAIN=${API_DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}
NGINX_SITE_NAME=${NGINX_SITE_NAME:-websearch}
WEBSEARCH_API_URL=https://${API_DOMAIN}
EOF

    chmod 600 "$env_file"
    ok "已写入 ${env_file}"
}

update_searxng_secret() {
    local settings="$PROJECT_ROOT/deploy/searxng/settings.yml"
    if [[ ! -f "$settings" ]]; then
        warn "未找到 ${settings}，跳过 SearXNG 密钥同步。"
        return 0
    fi

    if grep_safe -q 'secret_key:' "$settings"; then
        sed -i "s|secret_key:.*|secret_key: \"${SEARXNG_SECRET_KEY}\"|" "$settings"
    else
        warn "settings.yml 中无 secret_key 字段，请手动检查。"
        return 0
    fi

    ok "已同步 SearXNG secret_key → deploy/searxng/settings.yml"
}

configure_redis() {
    step "[1/4] Redis 配置"

    local detected=""
    if detected="$(describe_existing_redis 2>/dev/null)"; then
        info "检测到已有 Redis:"
        echo "  ${detected}"
        echo ""
        if prompt_yn "复用已有 Redis（不新建容器）?" "y"; then
            USE_BUILTIN_REDIS=false
            prompt REDIS_CONNECTION "Redis 连接串" "$(default_external_redis_connection)"
            ok "将连接外部 Redis: ${REDIS_CONNECTION}"
            return
        fi
    else
        info "未检测到 6379 端口上的 Redis。"
        if prompt_yn "是否使用外部 Redis（非本项目容器）?" "n"; then
            USE_BUILTIN_REDIS=false
            prompt REDIS_CONNECTION "Redis 连接串" "$(default_external_redis_connection)"
            ok "将连接外部 Redis: ${REDIS_CONNECTION}"
            return
        fi
    fi

    USE_BUILTIN_REDIS=true
    REDIS_CONNECTION="redis:6379,abortConnect=false"
    ok "将新建内置 Redis 容器"
}

configure_postgres() {
    step "[2/4] PostgreSQL 配置"

    local detected=""
    if detected="$(describe_existing_postgres 2>/dev/null)"; then
        info "检测到已有 PostgreSQL:"
        echo "  ${detected}"
        echo ""
        if prompt_yn "复用已有 PostgreSQL（不新建容器）?" "y"; then
            USE_BUILTIN_POSTGRES=false
            echo ""
            echo "请输入已有 PostgreSQL 的连接信息（API 容器通过 host.docker.internal 访问宿主机端口）。"
            prompt PG_HOST "数据库 Host" "${HOST_GATEWAY}"
            prompt PG_PORT "数据库 Port" "5432"
            prompt PG_DATABASE "数据库名" "websearch"
            prompt PG_USERNAME "用户名" "websearch"
            while [[ -z "${PG_PASSWORD:-}" ]]; do
                read -r -s -p "PostgreSQL 密码: " PG_PASSWORD
                echo ""
                [[ -z "${PG_PASSWORD}" ]] && warn "密码不能为空。"
            done
            POSTGRES_PASSWORD="${PG_PASSWORD}"
            POSTGRES_CONNECTION="Host=${PG_HOST};Port=${PG_PORT};Database=${PG_DATABASE};Username=${PG_USERNAME};Password=${PG_PASSWORD}"
            ok "将连接外部 PostgreSQL"
            echo ""
            warn "请先在已有 PostgreSQL 中创建库和用户（否则 API 会一直起不来）:"
            echo "  CREATE DATABASE ${PG_DATABASE};"
            echo "  CREATE USER ${PG_USERNAME} WITH PASSWORD '你的密码';"
            echo "  GRANT ALL PRIVILEGES ON DATABASE ${PG_DATABASE} TO ${PG_USERNAME};"
            return
        fi
    else
        info "未检测到 5432 端口上的 PostgreSQL。"
        if prompt_yn "是否使用外部 PostgreSQL（非本项目容器）?" "n"; then
            USE_BUILTIN_POSTGRES=false
            prompt PG_HOST "数据库 Host" "${HOST_GATEWAY}"
            prompt PG_PORT "数据库 Port" "5432"
            prompt PG_DATABASE "数据库名" "websearch"
            prompt PG_USERNAME "用户名" "websearch"
            while [[ -z "${PG_PASSWORD:-}" ]]; do
                read -r -s -p "PostgreSQL 密码: " PG_PASSWORD
                echo ""
                [[ -z "${PG_PASSWORD}" ]] && warn "密码不能为空。"
            done
            POSTGRES_PASSWORD="${PG_PASSWORD}"
            POSTGRES_CONNECTION="Host=${PG_HOST};Port=${PG_PORT};Database=${PG_DATABASE};Username=${PG_USERNAME};Password=${PG_PASSWORD}"
            ok "将连接外部 PostgreSQL"
            echo ""
            warn "请先在已有 PostgreSQL 中创建库和用户（否则 API 会一直起不来）:"
            echo "  CREATE DATABASE ${PG_DATABASE};"
            echo "  CREATE USER ${PG_USERNAME} WITH PASSWORD '你的密码';"
            echo "  GRANT ALL PRIVILEGES ON DATABASE ${PG_DATABASE} TO ${PG_USERNAME};"
            return
        fi
    fi

    USE_BUILTIN_POSTGRES=true
    echo ""
    echo "内置 PostgreSQL 密码（直接回车自动生成）:"
    prompt POSTGRES_PASSWORD "PostgreSQL 密码" "" "true"
    [[ -z "${POSTGRES_PASSWORD}" ]] && POSTGRES_PASSWORD="$(generate_secret)"
    POSTGRES_CONNECTION="Host=postgres;Port=5432;Database=websearch;Username=websearch;Password=${POSTGRES_PASSWORD}"
    ok "将新建内置 PostgreSQL 容器"
}

run_configure_env_interactive() {
    configure_redis
    configure_postgres

    step "[3/4] 其他密钥与 API Key"

    prompt SEARXNG_SECRET_KEY "SearXNG 密钥" "" "true"
    [[ -z "${SEARXNG_SECRET_KEY}" ]] && SEARXNG_SECRET_KEY="$(generate_secret)"
    ok "SearXNG 密钥已设置"

    prompt_optional FIRECRAWL_API_KEY "Firecrawl API Key"
    prompt_optional JINA_API_KEY "Jina API Key"

    prompt CACHE_SEARCH_TTL "搜索缓存 TTL（秒）" "7200"
    prompt CACHE_SCRAPE_TTL "抓取缓存 TTL（秒）" "86400"

    step "[4/4] 域名与 HTTPS"

    echo "请确保域名 A 记录已指向本 VPS IP。"
    echo ""

    prompt API_DOMAIN "API 域名（如 api.example.com）" ""
    CERTBOT_EMAIL=""
    if letsencrypt_cert_exists "$API_DOMAIN"; then
        ok "检测到已有 HTTPS 证书 (/etc/letsencrypt/live/${API_DOMAIN}/)，将直接复用，无需填写邮箱"
    else
        prompt CERTBOT_EMAIL "Certbot 邮箱（HTTPS 证书到期提醒）" ""
    fi
    NGINX_SITE_NAME="websearch"

    step "确认配置"

    echo "  Redis:             $([[ "${USE_BUILTIN_REDIS}" == "true" ]] && echo '新建容器' || echo "复用外部 → ${REDIS_CONNECTION}")"
    echo "  PostgreSQL:        $([[ "${USE_BUILTIN_POSTGRES}" == "true" ]] && echo '新建容器' || echo "复用外部 → Host=${PG_HOST:-${HOST_GATEWAY}}")"
    echo "  SearXNG 密钥:      (已设置)"
    echo "  Firecrawl Key:     ${FIRECRAWL_API_KEY:-<未设置>}"
    echo "  Jina Key:          ${JINA_API_KEY:-<未设置>}"
    echo "  搜索缓存 TTL:      ${CACHE_SEARCH_TTL}s"
    echo "  抓取缓存 TTL:      ${CACHE_SCRAPE_TTL}s"
    echo "  API 域名:          https://${API_DOMAIN}"
    if letsencrypt_cert_exists "$API_DOMAIN"; then
        echo "  HTTPS 证书:        复用已有"
    else
        echo "  Certbot 邮箱:      ${CERTBOT_EMAIL}"
    fi
    echo ""

    if ! prompt_yn "确认写入 .env 并开始部署?" "y"; then
        info "已取消。"
        exit 0
    fi

    write_env_file
    update_searxng_secret
}

run_configure_env_from_env() {
    : "${API_DOMAIN:?API_DOMAIN required}"
    if ! letsencrypt_cert_exists "${API_DOMAIN}"; then
        : "${CERTBOT_EMAIL:?CERTBOT_EMAIL required when no existing certificate for API_DOMAIN}"
    fi
    CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"

    USE_BUILTIN_REDIS="${USE_BUILTIN_REDIS:-true}"
    USE_BUILTIN_POSTGRES="${USE_BUILTIN_POSTGRES:-true}"
    SEARXNG_SECRET_KEY="${SEARXNG_SECRET_KEY:-$(generate_secret)}"
    FIRECRAWL_API_KEY="${FIRECRAWL_API_KEY:-}"
    JINA_API_KEY="${JINA_API_KEY:-}"
    CACHE_SEARCH_TTL="${CACHE_SEARCH_TTL:-7200}"
    CACHE_SCRAPE_TTL="${CACHE_SCRAPE_TTL:-86400}"
    NGINX_SITE_NAME="${NGINX_SITE_NAME:-websearch}"

    if [[ "${USE_BUILTIN_REDIS}" == "true" ]]; then
        REDIS_CONNECTION="${REDIS_CONNECTION:-redis:6379,abortConnect=false}"
    else
        REDIS_CONNECTION="${REDIS_CONNECTION:-$(default_external_redis_connection)}"
    fi

    if [[ "${USE_BUILTIN_POSTGRES}" == "true" ]]; then
        : "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required for builtin postgres}"
        POSTGRES_CONNECTION="${POSTGRES_CONNECTION:-Host=postgres;Port=5432;Database=websearch;Username=websearch;Password=${POSTGRES_PASSWORD}}"
    else
        : "${POSTGRES_CONNECTION:?POSTGRES_CONNECTION required for external postgres}"
        POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
    fi

    write_env_file
    update_searxng_secret
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cd "$PROJECT_ROOT"
    if [[ -n "${API_DOMAIN:-}" ]]; then
        run_configure_env_from_env
    else
        run_configure_env_interactive
    fi
fi
