// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebSearch.Application.Data;

#nullable disable

namespace WebSearch.Application.Data.Migrations
{
    [DbContext(typeof(WebSearchDbContext))]
    [Migration("20260610000000_SplitLogs")]
    partial class SplitLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebSearch.Application.Data.SearchLog", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                b.Property<bool>("CacheHit").HasColumnType("boolean").HasColumnName("cache_hit");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<long>("DurationMs").HasColumnType("bigint").HasColumnName("duration_ms");
                b.Property<string>("NormalizedQuery").IsRequired().HasColumnType("text").HasColumnName("normalized_query");
                b.Property<string>("Query").IsRequired().HasColumnType("text").HasColumnName("query");
                b.Property<int>("ResultCount").HasColumnType("integer").HasColumnName("result_count");
                b.Property<string>("Source").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("source");
                b.HasKey("Id").HasName("PK_search_logs");
                b.HasIndex("CreatedAt").HasDatabaseName("IX_search_logs_created_at");
                b.HasIndex("Source", "CreatedAt").HasDatabaseName("IX_search_logs_source_created_at");
                b.ToTable("search_logs");
            });

            modelBuilder.Entity("WebSearch.Application.Data.ScrapeLog", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                b.Property<bool>("CacheHit").HasColumnType("boolean").HasColumnName("cache_hit");
                b.Property<int>("ContentLength").HasColumnType("integer").HasColumnName("content_length");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<long>("DurationMs").HasColumnType("bigint").HasColumnName("duration_ms");
                b.Property<bool>("Success").HasColumnType("boolean").HasColumnName("success");
                b.Property<string>("Source").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("source");
                b.Property<string>("Url").IsRequired().HasColumnType("text").HasColumnName("url");
                b.HasKey("Id").HasName("PK_scrape_logs");
                b.HasIndex("Source", "CreatedAt").HasDatabaseName("IX_scrape_logs_source_created_at");
                b.HasIndex("Url", "CreatedAt").HasDatabaseName("IX_scrape_logs_url_created_at");
                b.ToTable("scrape_logs");
            });
#pragma warning restore 612, 618
        }
    }
}
